[package]
name = "redis_del_all_keys"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
error-chain = "=0.10.0"
log = "=0.3.8"
log4rs = "=0.7.0"
redis = "=0.8.0"
simple_logger = "=0.4.0"
structopt = "=0.0.5"
structopt-derive = "=0.0.5"
url = "=1.5.0"